### ISSUE TITLE
Argument of type '(ExecutedOrder | PendingOrder)[]' is not assignable to parameter of type 'ExecutedOrder[]

### ISSUE THREAD

**Issue by fizikst** [debut-js/Plugins#5]
Hi men, at compile time returning error binded with different types.
![Screenshot_25](https://user-images.githubusercontent.com/1951304/136031236-e622c626-2b1e-47cb-afed-dfe6dc4583e6.png)

**Comment by BusinessDuck** [comment]
Looks like you need to update @debut/types, it was fixed.

**Comment by BusinessDuck** [comment]
fixed with https://github.com/debut-js/Plugins/commit/fa2a776e1825e2117a9f74bb7099c39151f95c5e
