### ISSUE TITLE
brain_js_1.CrossValidate is not a constructor

### ISSUE THREAD

**Issue by fizikst** [debut-js/Plugins#6]
During testing start with flag "--neuroTrain" returning next error :
"TypeError: brain_js_1.CrossValidate is not a constructor"
![Screenshot_26](https://user-images.githubusercontent.com/1951304/136032024-8ee4dcea-ebf7-4f3f-a1a1-2597225e1d42.png)

**Initialize plugin**

_class MyStrategy_
![Screenshot_27](https://user-images.githubusercontent.com/1951304/136033646-eb0c8be5-5022-467e-a751-df4fd004a3b1.png)

_async onCandle_
![Screenshot_28](https://user-images.githubusercontent.com/1951304/136033816-ef704736-6c35-4761-8610-d5068bf4e88b.png)

**Comment by fizikst** [comment]
I did it, it works for me,but is not sure what this right solution
![Screenshot_34](https://user-images.githubusercontent.com/1951304/136502989-fcda3ffe-6e19-4b34-9ce4-5bd5eec982f7.png)
on

**Comment by BusinessDuck** [comment]
Looks good, could you make a PR?

**Comment by BusinessDuck** [comment]
That's aswell trouble with brainjs beta 3, closed, version hard fixed to beta 2 now
