### ISSUE TITLE
Could not find a declaration file for module 'brain.js'.

### ISSUE THREAD

**Issue by fizikst** [debut-js/Plugins#7]
I get an error when running the command:
![Screenshot_32](https://user-images.githubusercontent.com/1951304/136501577-1fc09042-89bb-4b3c-a60a-e6b33d8e4696.png)

I did it, it works for me,but is not sure what this right solution
![Screenshot_33](https://user-images.githubusercontent.com/1951304/136501871-716ec975-4c50-4741-a054-71154e58f899.png)

**Comment by BusinessDuck** [comment]
i reprodice it, regarding with 2.0.0-beta.3 brain.js , fix to beta 2 yet
