### ISSUE TITLE
Providing the list of orders in strategies would make plugins like virtual-take and dynamic-take useless

### ISSUE THREAD

**Issue by solarfrantz** [debut-js/Plugins#8]
Right now we don't have the order(s) in the "this" arguments passed on to the strategies `onCandle` method (eg: https://github.com/debut-js/Strategies/blob/master/src/strategies/stoch-macd/bot.ts#L108) and access them as `this.orders` instead of doing things via `this.plugins.dynamicTakes.setForOrder(order.cid, take, stop)`;

If we would, than everyone could implement their own math based on the trade profit, duration etc.
For example, right now it's possible with only with the `dynamic-takes` plugin to set the stop/take numeric value, instead of percentage.
But providing the orders in the strategies would be much more powerful.

**Comment by BusinessDuck** [comment]
@solarfrantz can you send conceptual code as you want to be?

**Comment by BusinessDuck** [comment]
closed by inactivity
